// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEO1q8cDysbdNux7Zqb7-LpK0DTeoaURw',
    appId: '1:400522539096:web:010d32e45cc24175261a2d',
    messagingSenderId: '400522539096',
    projectId: 'fawatiri-f2521',
    authDomain: 'fawatiri-f2521.firebaseapp.com',
    storageBucket: 'fawatiri-f2521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGY7UkMpNpzImPHc6uYMdGjF6PcK1p040',
    appId: '1:400522539096:android:0fa8210d965d1ff0261a2d',
    messagingSenderId: '400522539096',
    projectId: 'fawatiri-f2521',
    storageBucket: 'fawatiri-f2521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7AIbzq7lEtjlLRmMesA2tgeRAImEXuIs',
    appId: '1:400522539096:ios:b1895af53654ae41261a2d',
    messagingSenderId: '400522539096',
    projectId: 'fawatiri-f2521',
    storageBucket: 'fawatiri-f2521.firebasestorage.app',
    iosBundleId: 'com.example.fawatiri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7AIbzq7lEtjlLRmMesA2tgeRAImEXuIs',
    appId: '1:400522539096:ios:b1895af53654ae41261a2d',
    messagingSenderId: '400522539096',
    projectId: 'fawatiri-f2521',
    storageBucket: 'fawatiri-f2521.firebasestorage.app',
    iosBundleId: 'com.example.fawatiri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEO1q8cDysbdNux7Zqb7-LpK0DTeoaURw',
    appId: '1:400522539096:web:ec4c6a2e261fb81b261a2d',
    messagingSenderId: '400522539096',
    projectId: 'fawatiri-f2521',
    authDomain: 'fawatiri-f2521.firebaseapp.com',
    storageBucket: 'fawatiri-f2521.firebasestorage.app',
  );
}
